enum Role {
  SUPER_ADMIN
}

extend type User {
  roles: [Role!]!
}

enum UserSort {
  CREATED_AT_DESC
  CREATED_AT_ASC
}

type PageInfo {
  hasNextPage: Boolean!
  endCursor: String
}

type UserEdge {
  cursor: String!
  node: User!
}

type UserConnection {
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

extend type Query {
  adminListUsers(query: String, sortBy: UserSort = CREATED_AT_DESC, first: Int = 20, after: String): UserConnection!
  adminGetUser(id: ID!): User
}

input AdminUpdateUserInput {
  displayName: String
  photoURL: String
  phoneNumber: String
}

extend type Mutation {
  adminUpdateUser(id: ID!, input: AdminUpdateUserInput!): User!
  adminDeleteUser(id: ID!, confirm: String!): Boolean!
  adminResetPassword(id: ID!): Boolean!
}


