 

enum UserSort {
  CREATED_AT_DESC
  CREATED_AT_ASC
}

type PageInfo {
  hasNextPage: Boolean!
  endCursor: String
}

type UserEdge {
  cursor: String!
  node: User!
}

type UserConnection {
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

extend type Query {
  adminListUsers(query: String, sortBy: UserSort = CREATED_AT_DESC, first: Int = 20, after: String): UserConnection!
  adminGetUser(uid: ID!): User
}

input AdminUpdateUserInput {
  email: String
  emailVerified: Boolean
  phoneNumber: String
  password: String
  displayName: String
  photoURL: String
  disabled: Boolean
}

extend type Mutation {
  adminUpdateUser(uid: ID!, input: AdminUpdateUserInput!): User!
  adminDeleteUser(uid: ID!): Boolean!
  adminResetPassword(uid: ID!): Boolean!
}


