extend type Query {
  me: User
}

extend type Mutation {
  loginWithIdToken(idToken: String!): AuthPayload!
  updateProfile(displayName: String, photoURL: String): User!
}

type User {
  uid: ID!
  email: String
  emailVerified: Boolean!
  displayName: String
  photoURL: String
  phoneNumber: String
  lastLoginProvider: String
  identities: [UserIdentity!]!
}

type AuthPayload {
  user: User!
  accessToken: String
}

type UserIdentity {
  providerId: String!
  providerUid: String!
  lastUsedAt: String
}


