extend type Query {
  me: User
}

extend type Mutation {
  loginWithIdToken(idToken: String!): AuthPayload!
  updateProfile(displayName: String, photoURL: String): User!
}

type Permission {
  id: ID!
  name: String!
  description: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type Role {
  id: ID!
  name: String!
  description: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type User {
  uid: ID!
  email: String
  emailVerified: Boolean!
  displayName: String
  photoURL: String
  phoneNumber: String
  lastLoginProvider: String
  identities: [UserIdentity!]!
  createdAt: Timestamp!
  roles: [Role!]!
  permissions: [String!]!
}

type AuthPayload {
  user: User!
  accessToken: String
}

type UserIdentity {
  providerId: String!
  providerUid: String!
  lastUsedAt: Timestamp
}


